file_format: "0.3"
disabled: false
resource:
  schema_url: https://opentelemetry.io/schemas/1.26.0
  attributes:
    - name: service.name
      value: "${SERVICE_NAME}"
    - name: service.version
      value: "${SERVICE_VERSION}"
    - name: other
      value: "one-more"
tracer_provider:
  processors:
    - simple:
        exporter:
          console: {}
    - batch:
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: https://api.honeycomb.io:443
            headers:
              - name: x-honeycomb-team
                value: "${HONEYCOMB_API_KEY}"
            # Configure compression.
            compression: gzip
            # Configure max time (in milliseconds) to wait for each export.
            timeout: 10000

meter_provider:
  readers:
    - pull:
        exporter:
          prometheus:
            host: localhost
            port: 9999
    - periodic:
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: https://api.honeycomb.io:443
            headers:
              - name: x-honeycomb-team
                value: "${HONEYCOMB_API_KEY}"
            # Configure compression.
            compression: gzip
            # Configure max time (in milliseconds) to wait for each export.
            timeout: 10000
  views:

logger_provider:
  processors:
    - simple:
        exporter:
          console: {}
    - batch:
        exporter:
          # Configure exporter to be OTLP.
          otlp:
            # Configure protocol.
            protocol: http/protobuf
            # Configure endpoint.
            endpoint: https://api.honeycomb.io:443
            # Configure headers. Entries have higher priority than entries from .headers_list.
            headers:
              - name: x-honeycomb-team
                value: "${HONEYCOMB_API_KEY}"
            # Configure compression.
            compression: gzip
            # # Configure max time (in milliseconds) to wait for each export.
            timeout: 10000
