services:
  app1:
    build: ./
    environment:
      OTEL_SERVICE_NAME: app1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://oteltui:4318/
      OTEL_METRIC_EXPORT_INTERVAL: 5000
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
      - oteltui
      - prometheus

  app2:
    build: ./
    environment:
      OTEL_EXPERIMENTAL_CONFIG_FILE: /sdk-config.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./sdk-config.yaml:/sdk-config.yaml
    depends_on:
      - jaeger
      - oteltui
      - prometheus

  prometheus:
    image: prom/prometheus:v3.0.0-rc.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--web.enable-otlp-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - "16686:16686"
      - "14317:4317"
      - "14318:4318"

  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    ports:
      - "4318:4318"
