file_format: "0.1"

resource:
  attributes:
    - name: service.name
      value: app2

tracer_provider:
  processors:
    - batch:
        max_export_batch_size: 100
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: http://oteltui:4318/v1/traces
    - batch:
        exporter:
          otlp:
            protocol: grpc
            endpoint: http://jaeger:4317/
  sampler:
    parent_based:
      root:
        rule_based_routing:
          fallback_sampler:
            trace_id_ratio_based:
              ratio: 0.4
          span_kind: SERVER
          rules:
            - action: DROP
              attribute: url.path
              pattern: /actuator/health

meter_provider:
  readers:
    - periodic:
        interval: 5000
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    - periodic:
        interval: 5000
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: http://oteltui:4318/v1/metrics
  views:
    - selector:
        instrument_name: jvm.gc.duration
      stream:
        aggregation:
          drop:
    - selector:
        instrument_name: http.server.request.duration
      stream:
        aggregation:
          explicit_bucket_histogram:
            boundaries:
              - 0.0
              - 1.0
              - 5.0
              - 10.0

logger_provider:
  processors:
    - batch:
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: http://oteltui:4318/v1/logs

instrumentation:
  java:
    logback-appender:
      experimental-log-attributes: true
